// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ssXInLiD4etgkdcmneOp4PS8KrbdXcs',
    appId: '1:1027113826493:android:bda57cebd678182a739fd4',
    messagingSenderId: '1027113826493',
    projectId: 'pushnot-c7ab8',
    storageBucket: 'pushnot-c7ab8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgDg71EPUj-TffLtGJ-NSyrWMY2ypB0c4',
    appId: '1:1027113826493:ios:3bd1c5889f49085b739fd4',
    messagingSenderId: '1027113826493',
    projectId: 'pushnot-c7ab8',
    storageBucket: 'pushnot-c7ab8.appspot.com',
    iosBundleId: 'com.example.dcard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgDg71EPUj-TffLtGJ-NSyrWMY2ypB0c4',
    appId: '1:1027113826493:ios:3bd1c5889f49085b739fd4',
    messagingSenderId: '1027113826493',
    projectId: 'pushnot-c7ab8',
    storageBucket: 'pushnot-c7ab8.appspot.com',
    iosBundleId: 'com.example.dcard',
  );
}
